aspnet/DataProtection

- build.cmd
- build.sh
- src/Microsoft.AspNet.Cryptography.Internal/CryptoUtil.cs
- src/Microsoft.AspNet.Cryptography.Internal/SafeHandles/SafeHandleZeroOrMinusOneIsInvalid.cs
- src/Microsoft.AspNet.Cryptography.Internal/SafeHandles/SafeLibraryHandle.cs
- src/Microsoft.AspNet.Cryptography.Internal/SafeHandles/SafeNCryptKeyHandle.cs
- src/Microsoft.AspNet.Cryptography.Internal/SafeHandles/SecureLocalAllocHandle.cs
- src/Microsoft.AspNet.Cryptography.Internal/UnsafeBufferUtil.cs
- src/Microsoft.AspNet.Cryptography.Internal/UnsafeNativeMethods.cs
- src/Microsoft.AspNet.Cryptography.Internal/project.json
- src/Microsoft.AspNet.Cryptography.KeyDerivation/project.json
- src/Microsoft.AspNet.DataProtection.Azure/project.json
- src/Microsoft.AspNet.DataProtection/Cng/DpapiSecretSerializerHelper.cs
- src/Microsoft.AspNet.DataProtection/DataProtectionServiceCollectionExtensions.cs
- src/Microsoft.AspNet.DataProtection/Dpapi/DataProtectionScope.cs
- src/Microsoft.AspNet.DataProtection/Dpapi/ProtectedDataImpl.cs
- src/Microsoft.AspNet.DataProtection/Managed/ManagedAuthenticatedEncryptor.cs
- src/Microsoft.AspNet.DataProtection/XmlEncryption/DpapiNGXmlEncryptor.cs
- src/Microsoft.AspNet.DataProtection/XmlEncryption/DpapiXmlEncryptor.cs
- src/Microsoft.AspNet.DataProtection/project.json
- test/Microsoft.AspNet.Cryptography.Internal.Test/project.json
- test/Microsoft.AspNet.Cryptography.KeyDerivation.Test/project.json
- test/Microsoft.AspNet.DataProtection.Test/project.json
Prepping to be merged once ready.
> Update aspnet50/aspnetcore50 => dnx50/dnxcore50.

- src/Microsoft.AspNet.DataProtection.Interfaces/DataProtectionExtensions.cs
- src/Microsoft.AspNet.DataProtection.Interfaces/Properties/Resources.Designer.cs
- src/Microsoft.AspNet.DataProtection.Interfaces/Resources.resx
- src/Microsoft.AspNet.DataProtection.Interfaces/project.json
- src/Microsoft.AspNet.DataProtection.SystemWeb/CompatibilityDataProtector.cs
- src/Microsoft.AspNet.DataProtection.SystemWeb/DataProtectionStartup.cs
- src/Microsoft.AspNet.DataProtection/DataProtectionConfiguration.cs
- src/Microsoft.AspNet.DataProtection/DataProtectionServiceDescriptors.cs
- src/Microsoft.AspNet.DataProtection/DataProtectionServices.cs
- src/Microsoft.AspNet.DataProtection/LoggingServiceProviderExtensions.cs
- src/Microsoft.AspNet.DataProtection/project.json
- test/Microsoft.AspNet.DataProtection.Interfaces.Test/DataProtectionExtensionsTests.cs
- Add helpful extension methods to Interfaces project
- Auto heuristic detection now writes default protection settings to the ILogger
- Cleanup dead methods / add useful methods in DataProtectionConfiguration
- Update System.Web compatibility project to allow mapping MachineKey.Protect directly to IDataProtector.Protect
> Continued API improvements and refactoring

- src/Microsoft.AspNet.DataProtection/DataProtectionServices.cs
Fixes https://github.com/aspnet/DataProtection/issues/68.
> Skip registry checks on non-Windows platforms

- src/Microsoft.AspNet.DataProtection/Repositories/FileSystemXmlRepository.cs
If LOCALAPPDATA and USERPROFILE are both null (as is the case on
Linux/OSX) use "$HOME/.aspnet" as the root folder for data protection
keys
Fixes #76
> Use $HOME as a possible storage location

- makefile.shade
- src/Microsoft.AspNet.Cryptography.Internal/Properties/AssemblyInfo.cs
- src/Microsoft.AspNet.DataProtection.SystemWeb/project.json
- test/Microsoft.AspNet.DataProtection.Extensions.Test/DataProtectionProviderTests.cs
- test/Microsoft.AspNet.DataProtection.Extensions.Test/project.json
- test/Microsoft.AspNet.DataProtection.Test/KeyManagement/XmlKeyManagerTests.cs
- test/Microsoft.AspNet.DataProtection.Test/Managed/ManagedAuthenticatedEncryptorTests.cs
- test/Microsoft.AspNet.DataProtection.Test/XmlEncryption/CertificateXmlEncryptionTests.cs
Summary of the changes
- Skip building Microsoft.AspNet.DataProtection.SystemWeb
- Fix/disable unit tests
#91
> Fix build on Linux

- test/Microsoft.AspNet.Cryptography.Internal.Test/project.json
- test/Microsoft.AspNet.Cryptography.KeyDerivation.Test/project.json
> Enable some tests on CoreCLR.

- Provision-AutoGenKeys.ps1
Based on https://support.microsoft.com/en-us/kb/2915218
Usage `.\Provision-AutoGenKeys.ps1 DefaultAppPool`
@muratg @blowdart @Eilon
> Add script to add AutoGenKeys section and UCL for it

- src/Microsoft.AspNet.DataProtection.Extensions/DataProtectionProvider.cs
- src/Microsoft.AspNet.DataProtection/DataProtectionServiceCollectionExtensions.cs
cc @Tratcher This differs a bit from all the other repos, but I just left things mostly alone and turned Configure into an overload of Add like everyone else.
> ConfigureDP => AddDP

- .gitattributes
- .gitignore
- .travis.yml
- appveyor.yml
- build.cmd
- build.sh
- makefile.shade
- test/Microsoft.AspNet.Cryptography.Internal.Test/project.json
- test/Microsoft.AspNet.Cryptography.KeyDerivation.Test/project.json
- test/Microsoft.AspNet.DataProtection.Abstractions.Test/project.json
- test/Microsoft.AspNet.DataProtection.Extensions.Test/project.json
- test/Microsoft.AspNet.DataProtection.Test/project.json
> Build with dotnet

- test/Microsoft.AspNetCore.DataProtection.Test/StringLoggerFactory.cs
https://github.com/aspnet/Logging/issues/331
> React to Logging API changes

- NuGetPackageVerifier.json
- src/Microsoft.AspNetCore.Cryptography.Internal/project.json
- src/Microsoft.AspNetCore.Cryptography.KeyDerivation/project.json
- src/Microsoft.AspNetCore.DataProtection.Abstractions/DataProtectionExtensions.cs
- src/Microsoft.AspNetCore.DataProtection.Abstractions/IDataProtectionProvider.cs
- src/Microsoft.AspNetCore.DataProtection.Abstractions/IDataProtector.cs
- src/Microsoft.AspNetCore.DataProtection.Abstractions/project.json
- src/Microsoft.AspNetCore.DataProtection.Extensions/DataProtectionExtensions.cs
- src/Microsoft.AspNetCore.DataProtection.Extensions/ITimeLimitedDataProtector.cs
- src/Microsoft.AspNetCore.DataProtection.Extensions/project.json
- src/Microsoft.AspNetCore.DataProtection.SystemWeb/project.json
- src/Microsoft.AspNetCore.DataProtection/AuthenticatedEncryption/ConfigurationModel/ManagedAuthenticatedEncryptorConfiguration.cs
- src/Microsoft.AspNetCore.DataProtection/DataProtectionConfiguration.cs
- src/Microsoft.AspNetCore.DataProtection/RegistryPolicyResolver.cs
- src/Microsoft.AspNetCore.DataProtection/Repositories/RegistryXmlRepository.cs
- src/Microsoft.AspNetCore.DataProtection/XmlEncryption/DpapiNGXmlDecryptor.cs
- src/Microsoft.AspNetCore.DataProtection/XmlEncryption/DpapiXmlDecryptor.cs
- src/Microsoft.AspNetCore.DataProtection/XmlEncryption/EncryptedXmlDecryptor.cs
- src/Microsoft.AspNetCore.DataProtection/XmlEncryption/NullXmlDecryptor.cs
- src/Microsoft.AspNetCore.DataProtection/project.json
> Enabled xml doc generation

- README.md
- src/Microsoft.AspNetCore.Cryptography.Internal/project.json
- src/Microsoft.AspNetCore.Cryptography.KeyDerivation/project.json
- src/Microsoft.AspNetCore.DataProtection.Abstractions/project.json
- src/Microsoft.AspNetCore.DataProtection.Extensions/project.json
- src/Microsoft.AspNetCore.DataProtection.Sources/project.json
- src/Microsoft.AspNetCore.DataProtection.SystemWeb/CompatibilityDataProtector.cs
- src/Microsoft.AspNetCore.DataProtection.SystemWeb/DataProtectionStartup.cs
- src/Microsoft.AspNetCore.DataProtection.SystemWeb/project.json
- src/Microsoft.AspNetCore.DataProtection.SystemWeb/web.config.transform
- src/Microsoft.AspNetCore.DataProtection/project.json
> Fix package metadata

- test/Microsoft.AspNetCore.Cryptography.Internal.Test/project.json
- test/Microsoft.AspNetCore.Cryptography.KeyDerivation.Test/project.json
- test/Microsoft.AspNetCore.DataProtection.Abstractions.Test/project.json
- test/Microsoft.AspNetCore.DataProtection.Extensions.Test/DataProtectionProviderTests.cs
- test/Microsoft.AspNetCore.DataProtection.Extensions.Test/project.json
- test/Microsoft.AspNetCore.DataProtection.Test/Repositories/FileSystemXmlRepositoryTests.cs
- test/Microsoft.AspNetCore.DataProtection.Test/XmlEncryption/CertificateXmlEncryptionTests.cs
- test/Microsoft.AspNetCore.DataProtection.Test/XmlEncryption/DpapiXmlEncryptionTests.cs
- test/Microsoft.AspNetCore.DataProtection.Test/project.json
> Migrate tests/samples/tools to portable

- makefile.shade
> Don't break the CI.

- src/Microsoft.AspNetCore.DataProtection.Abstractions/DataProtectionCommonExtensions.cs
- src/Microsoft.AspNetCore.DataProtection.Extensions/DataProtectionAdvancedExtensions.cs
- src/Microsoft.AspNetCore.DataProtection/DataProtectionUtilityExtensions.cs
- test/Microsoft.AspNetCore.DataProtection.Abstractions.Test/DataProtectionCommonExtensionsTests.cs
- test/Microsoft.AspNetCore.DataProtection.Extensions.Test/DataProtectionAdvancedExtensionsTests.cs
- test/Microsoft.AspNetCore.DataProtection.Test/DataProtectionUtilityExtensionsTests.cs
- Also updated test class names to reflect new extension naming.
#148 
/cc @ajaybhargavb FYI, will merge shortly.
> Unique-ify extension types to not be ambiguous.

- test/Microsoft.AspNetCore.DataProtection.Test/RegistryPolicyResolverTests.cs
- test/Microsoft.AspNetCore.DataProtection.Test/Repositories/RegistryXmlRepositoryTests.cs
- test/Microsoft.AspNetCore.DataProtection.Test/project.json
Part of https://github.com/aspnet/PlatformAbstractions/issues/34
> Replace PlatformAbstractions with RuntimeInformation

- src/Microsoft.AspNetCore.DataProtection/ActivatorExtensions.cs
- src/Microsoft.AspNetCore.DataProtection/DataProtectionServiceCollectionExtensions.cs
- src/Microsoft.AspNetCore.DataProtection/RC1ForwardingActivator.cs
- src/Microsoft.AspNetCore.DataProtection/SimpleActivator.cs
- test/Microsoft.AspNetCore.DataProtection.Test/RC1ForwardingActivatorTests.cs
https://github.com/aspnet/DataProtection/issues/153
> Add fallback to support rc1 keys

- test/Microsoft.AspNetCore.DataProtection.Extensions.Test/Properties/AssemblyInfo.cs
> Try disabling running tests in parallel to fix System_UsesProvidedDirectoryAndCertificate 

- Provision-AutoGenKeys.ps1
Now requires `WebAdministration` powershell module to get information.
@blowdart @shirhatti
> Detect pool user in script

- src/Microsoft.AspNetCore.DataProtection/DataProtectionServiceCollectionExtensions.cs
> Use TryAdd to add services

- build/dependencies.props
- src/Microsoft.AspNetCore.DataProtection.AzureStorage/Microsoft.AspNetCore.DataProtection.AzureStorage.csproj
@pakrym has been volunteered to test this.
cc @Eilon
> Update WindowsAzure.Storage version

- src/Microsoft.AspNetCore.DataProtection/DataProtectionUtilityExtensions.cs
- src/Microsoft.AspNetCore.DataProtection/Microsoft.AspNetCore.DataProtection.csproj
- test/Microsoft.AspNetCore.DataProtection.Test/DataProtectionUtilityExtensionsTests.cs
https://github.com/aspnet/Security/issues/1201#issuecomment-299541453
This functionality is moving into Hosting. Expect a Hosting PR shortly.
> Remove IHostingEnvironment dependency

- src/Microsoft.AspNetCore.DataProtection.AzureStorage/baseline.netcore.json
#212 
@dougbu 
Note the base branch is `rel/1.1.2`.
> Generated api check baselines

- src/Microsoft.AspNetCore.DataProtection/AuthenticatedEncryption/AuthenticatedEncryptorFactory.cs
- src/Microsoft.AspNetCore.DataProtection/AuthenticatedEncryption/CngCbcAuthenticatedEncryptorFactory.cs
- src/Microsoft.AspNetCore.DataProtection/AuthenticatedEncryption/CngGcmAuthenticatedEncryptorFactory.cs
- src/Microsoft.AspNetCore.DataProtection/AuthenticatedEncryption/ManagedAuthenticatedEncryptorFactory.cs
- src/Microsoft.AspNetCore.DataProtection/DataProtectionBuilderExtensions.cs
> Added some missed doc comments

- build/dependencies.props
- korebuild-lock.txt
- src/Microsoft.AspNetCore.DataProtection/Microsoft.AspNetCore.DataProtection.csproj
Add direct reference to `System.Security.Principal.Windows`
https://github.com/dotnet/corefx/issues/26390
Fixes: https://github.com/aspnet/Home/issues/2787
> Workaround corefx/26390
